// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Azure.Iot.Operations.Opc2WotLib
{
    using System.Collections.Generic;
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class WotThingModel : WotThingModelBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
 // Copyright (c) Microsoft Corporation. 
 // Licensed under the MIT License 
            this.Write("{\r\n  \"@context\": [\r\n    \"https://www.w3.org/2022/wot/td/v1.1\",\r\n    {\r\n");
 if (this.areUnitsInUse) { 
            this.Write("      \"qudt\": \"http://qudt.org/schema/qudt/\",\r\n");
 } 
            this.Write("      \"dov\": \"http://azure.com/DigitalOperations/vocab#\"\r\n    }\r\n  ],\r\n  \"@type\":" +
                    " \"tm:ThingModel\",\r\n  \"title\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.thingName));
            this.Write("\",\r\n  \"dov:typeRef\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.typeRef));
            this.Write("\",\r\n");
 if (this.isEvent) { 
            this.Write("  \"dov:isEvent\": true,\r\n");
 } 
 if (this.isComposite) { 
            this.Write("  \"dov:isComposite\": true,\r\n");
 } 
            this.Write("  \"links\": [\r\n");
 int ix1 = 1; foreach (string baseModelRef in this.baseModelRefs) { 
            this.Write("    {\r\n      \"rel\": \"tm:extends\",\r\n      \"href\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(baseModelRef));
            this.Write("\",\r\n      \"type\": \"application/tm+json\"\r\n    }");
            this.Write(this.ToStringHelper.ToStringWithCulture(ix1 < this.baseModelRefs.Count + this.linkInfos.Count ? "," : ""));
            this.Write("\r\n");
 ix1++; } 
 foreach (LinkInfo linkInfo in this.linkInfos) { 
            this.Write("    {\r\n      \"rel\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(linkInfo.Rel));
            this.Write("\",\r\n      \"dov:refName\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(linkInfo.RefName));
            this.Write("\",\r\n");
 if (linkInfo.RefType != null) { 
            this.Write("      \"dov:refType\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(linkInfo.RefType));
            this.Write("\",\r\n");
 } 
            this.Write("      \"href\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(linkInfo.Href));
            this.Write("\",\r\n      \"type\": \"application/tm+json\"\r\n    }");
            this.Write(this.ToStringHelper.ToStringWithCulture(ix1 < this.baseModelRefs.Count + this.linkInfos.Count ? "," : ""));
            this.Write("\r\n");
 ix1++; } 
            this.Write("  ],\r\n  \"schemaDefinitions\": {\r\n");
 ix1 = 1; foreach (OpcUaDataTypeEnum dataTypeEnum in this.dataTypeEnums) { 
            this.Write("    \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(dataTypeEnum.EffectiveName));
            this.Write("\": {\r\n      \"type\": \"object\",\r\n      \"dov:typeRef\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(dataTypeEnum.GetTypeRef()));
            this.Write("\",\r\n      \"const\": {\r\n");
 int ix2 = 1; foreach (KeyValuePair<string, OpcUaEnumValue> enumValue in dataTypeEnum.EnumValues) { 
            this.Write("        \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(enumValue.Value.SymbolicName ?? enumValue.Key));
            this.Write("\": ");
            this.Write(this.ToStringHelper.ToStringWithCulture(enumValue.Value.Value));
            this.Write(this.ToStringHelper.ToStringWithCulture(ix2 < dataTypeEnum.EnumValues.Count ? "," : ""));
            this.Write("\r\n");
 ix2++; } 
            this.Write("      },\r\n");
 if (dataTypeEnum.Description != null) { 
            this.Write("      \"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(dataTypeEnum.Description));
            this.Write("\",\r\n");
 } 
            this.Write("      \"properties\": {\r\n");
 ix2 = 1; foreach (KeyValuePair<string, OpcUaEnumValue> enumValue in dataTypeEnum.EnumValues) { 
            this.Write("        \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(enumValue.Value.SymbolicName ?? enumValue.Key));
            this.Write("\": {\r\n");
 if (enumValue.Value.Description != null) { 
            this.Write("          \"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(enumValue.Value.Description));
            this.Write("\",\r\n");
 } 
            this.Write("          \"type\": \"integer\"\r\n        }");
            this.Write(this.ToStringHelper.ToStringWithCulture(ix2 < dataTypeEnum.EnumValues.Count ? "," : ""));
            this.Write("\r\n");
 ix2++; } 
            this.Write("      }\r\n    }");
            this.Write(this.ToStringHelper.ToStringWithCulture(ix1 < this.dataTypeEnums.Count ? "," : ""));
            this.Write("\r\n");
 ix1++; } 
            this.Write("  },\r\n");
 if (this.properties.Any() || this.events.Any()) { 
            this.Write("  \"forms\": [\r\n");
 if (this.events.Any()) { 
            this.Write("    {\r\n      \"contentType\": \"application/json\",\r\n      \"dov:topic\": \"opcua/");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.specName));
            this.Write("/");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.thingName));
            this.Write("/events/{senderId}\",\r\n");
 if (this.inheritVars && this.baseModelRefs.Any()) { 
            this.Write("      \"dov:includeInherited\": true,\r\n");
 } 
            this.Write("      \"op\": \"subscribeallevents\"\r\n    }");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.properties.Any() ? "," : ""));
            this.Write("\r\n");
 } 
 if (this.properties.Any()) { 
 if (this.properties.Any(p => !p.ReadOnly)) { 
            this.Write("    {\r\n      \"contentType\": \"application/json\",\r\n      \"dov:topic\": \"opcua/");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.specName));
            this.Write("/");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.thingName));
            this.Write("/properties/write\",\r\n");
 if (this.inheritVars && this.baseModelRefs.Any()) { 
            this.Write("      \"dov:includeInherited\": true,\r\n");
 } 
            this.Write("      \"op\": \"writemultipleproperties\"\r\n    },\r\n");
 } 
            this.Write("    {\r\n      \"contentType\": \"application/json\",\r\n      \"dov:topic\": \"opcua/");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.specName));
            this.Write("/");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.thingName));
            this.Write("/properties/read\",\r\n");
 if (this.inheritVars && this.baseModelRefs.Any()) { 
            this.Write("      \"dov:includeInherited\": true,\r\n");
 } 
            this.Write("      \"op\": \"readallproperties\"\r\n    }\r\n");
 } 
            this.Write("  ],\r\n");
 } 
            this.Write("  \"actions\": {\r\n");
 this.PushIndent("    "); 
 ix1 = 1; foreach (WotAction action in this.actions) { 
            this.Write(this.ToStringHelper.ToStringWithCulture(action.TransformText()));
            this.Write(this.ToStringHelper.ToStringWithCulture(ix1 < this.actions.Count ? "," : ""));
            this.Write("\r\n");
 ix1++; } this.PopIndent(); 
            this.Write("  },\r\n  \"properties\": {\r\n");
 this.PushIndent("    "); 
 ix1 = 1; foreach (WotProperty property in this.properties) { 
            this.Write(this.ToStringHelper.ToStringWithCulture(property.TransformText()));
            this.Write(this.ToStringHelper.ToStringWithCulture(ix1 < this.properties.Count ? "," : ""));
            this.Write("\r\n");
 ix1++; } this.PopIndent(); 
            this.Write("  },\r\n  \"events\": {\r\n");
 this.PushIndent("    "); 
 ix1 = 1; foreach (WotEvent evt in this.events) { 
            this.Write(this.ToStringHelper.ToStringWithCulture(evt.TransformText()));
            this.Write(this.ToStringHelper.ToStringWithCulture(ix1 < this.events.Count ? "," : ""));
            this.Write("\r\n");
 ix1++; } this.PopIndent(); 
            this.Write("  }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class WotThingModelBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
